language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
notifications:
  recipients:
    - dan.wanek@gmail.com
branches:
  only:
    - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
